name: "Reports Engine Preprocessor"
description: "Runs the preprocessor package on a reports directory"
runs:
  using: "composite"
  steps:
    - name: Download CLI JAR 
      run: | 
        curl -L -o preprocessor.jar \
        https://github.com/pfadfinden/report-engine/releases/latest/download/preprocessor.jar 
      shell: bash

    - name: Run CLI
      shell: bash
      run: java -jar preprocessor.jar ${{ inputs.args }}
inputs:
  args:
    required: false
    default: ""
